/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "protodefs/ReservationsTable.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(koje_booker_hub_protobufs_ReservationsTable, koje_booker_hub_protobufs_ReservationsTable, 2)


PB_BIND(koje_booker_hub_protobufs_ReservationTableItem, koje_booker_hub_protobufs_ReservationTableItem, AUTO)



