/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MOTORDATA_PB_H_INCLUDED
#define PB_MOTORDATA_PB_H_INCLUDED
#include <nanopb/pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _CommandType {
    CommandType_UNKOWN_COMMAND = 0,
    CommandType_VEHICLE = 1,
    CommandType_SENSOR = 2
} CommandType;

/* Struct definitions */
typedef struct _Request {
    uint64_t id;
    CommandType command;
    float x_movement;
    float y_movement;
} Request;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _CommandType_MIN CommandType_UNKOWN_COMMAND
#define _CommandType_MAX CommandType_SENSOR
#define _CommandType_ARRAYSIZE ((CommandType)(CommandType_SENSOR+1))

#define Request_command_ENUMTYPE CommandType


/* Initializer values for message structs */
#define Request_init_default                     {0, _CommandType_MIN, 0, 0}
#define Request_init_zero                        {0, _CommandType_MIN, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Request_id_tag                           1
#define Request_command_tag                      2
#define Request_x_movement_tag                   3
#define Request_y_movement_tag                   4

/* Struct field encoding specification for nanopb */
#define Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    command,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    x_movement,        3) \
X(a, STATIC,   SINGULAR, FLOAT,    y_movement,        4)
#define Request_CALLBACK NULL
#define Request_DEFAULT NULL

extern const pb_msgdesc_t Request_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Request_fields &Request_msg

/* Maximum encoded size of messages (where known) */
#define MOTORDATA_PB_H_MAX_SIZE                  Request_size
#define Request_size                             23

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
