/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_KOJE_BOOKER_HUB_PROTOBUFS_PROTODEFS_NUMBEROFPAGES_PB_H_INCLUDED
#define PB_KOJE_BOOKER_HUB_PROTOBUFS_PROTODEFS_NUMBEROFPAGES_PB_H_INCLUDED
#include "nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _koje_booker_hub_protobufs_NumberOfPages {
    uint64_t id;
    uint32_t pages;
} koje_booker_hub_protobufs_NumberOfPages;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define koje_booker_hub_protobufs_NumberOfPages_init_default {0, 0}
#define koje_booker_hub_protobufs_NumberOfPages_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define koje_booker_hub_protobufs_NumberOfPages_id_tag 1
#define koje_booker_hub_protobufs_NumberOfPages_pages_tag 2

/* Struct field encoding specification for nanopb */
#define koje_booker_hub_protobufs_NumberOfPages_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   pages,             2)
#define koje_booker_hub_protobufs_NumberOfPages_CALLBACK NULL
#define koje_booker_hub_protobufs_NumberOfPages_DEFAULT NULL

extern const pb_msgdesc_t koje_booker_hub_protobufs_NumberOfPages_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define koje_booker_hub_protobufs_NumberOfPages_fields &koje_booker_hub_protobufs_NumberOfPages_msg

/* Maximum encoded size of messages (where known) */
#define KOJE_BOOKER_HUB_PROTOBUFS_PROTODEFS_NUMBEROFPAGES_PB_H_MAX_SIZE koje_booker_hub_protobufs_NumberOfPages_size
#define koje_booker_hub_protobufs_NumberOfPages_size 17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
