/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_KOJE_BOOKER_HUB_PROTOBUFS_PERIODICSTATUSUPDATE_PB_H_INCLUDED
#define PB_KOJE_BOOKER_HUB_PROTOBUFS_PERIODICSTATUSUPDATE_PB_H_INCLUDED
#include "nanopb/pb.h"
#include "ReservationStatus.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _koje_booker_hub_protobufs_PeriodicStatusUpdate {
    uint64_t time;
    int64_t timeZoneOffset;
    koje_booker_hub_protobufs_ReservationStatus status;
} koje_booker_hub_protobufs_PeriodicStatusUpdate;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define koje_booker_hub_protobufs_PeriodicStatusUpdate_init_default {0, 0, _koje_booker_hub_protobufs_ReservationStatus_MIN}
#define koje_booker_hub_protobufs_PeriodicStatusUpdate_init_zero {0, 0, _koje_booker_hub_protobufs_ReservationStatus_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define koje_booker_hub_protobufs_PeriodicStatusUpdate_time_tag 1
#define koje_booker_hub_protobufs_PeriodicStatusUpdate_timeZoneOffset_tag 2
#define koje_booker_hub_protobufs_PeriodicStatusUpdate_status_tag 3

/* Struct field encoding specification for nanopb */
#define koje_booker_hub_protobufs_PeriodicStatusUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   time,              1) \
X(a, STATIC,   SINGULAR, INT64,    timeZoneOffset,    2) \
X(a, STATIC,   SINGULAR, UENUM,    status,            3)
#define koje_booker_hub_protobufs_PeriodicStatusUpdate_CALLBACK NULL
#define koje_booker_hub_protobufs_PeriodicStatusUpdate_DEFAULT NULL

extern const pb_msgdesc_t koje_booker_hub_protobufs_PeriodicStatusUpdate_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define koje_booker_hub_protobufs_PeriodicStatusUpdate_fields &koje_booker_hub_protobufs_PeriodicStatusUpdate_msg

/* Maximum encoded size of messages (where known) */
#define KOJE_BOOKER_HUB_PROTOBUFS_PERIODICSTATUSUPDATE_PB_H_MAX_SIZE koje_booker_hub_protobufs_PeriodicStatusUpdate_size
#define koje_booker_hub_protobufs_PeriodicStatusUpdate_size 24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
