/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_KOJE_BOOKER_HUB_PROTOBUFS_REQUEST_PB_H_INCLUDED
#define PB_KOJE_BOOKER_HUB_PROTOBUFS_REQUEST_PB_H_INCLUDED
#include "nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _koje_booker_hub_protobufs_RequestType {
    koje_booker_hub_protobufs_RequestType_UNKNOWN_REQUEST_TYPE = 0,
    koje_booker_hub_protobufs_RequestType_GET_CURRENT_RESERVATION = 1,
    koje_booker_hub_protobufs_RequestType_GET_NEXT_RESERVATION = 2,
    koje_booker_hub_protobufs_RequestType_POST_EXTEND_RESERVATION = 3,
    koje_booker_hub_protobufs_RequestType_POST_RELEASE_RESERVATION = 4,
    koje_booker_hub_protobufs_RequestType_GET_PREVIOUS_RESERVATIONS = 5,
    koje_booker_hub_protobufs_RequestType_GET_NUM_OF_PAGES_FOR_PREVIOUS_RESERVATIONS = 6,
    koje_booker_hub_protobufs_RequestType_GET_UPCOMING_RESERVATIONS = 7,
    koje_booker_hub_protobufs_RequestType_GET_NUM_OF_PAGES_FOR_UPCOMING_RESERVATIONS = 8,
    koje_booker_hub_protobufs_RequestType_POST_CREATE_RESERVATION = 9,
    koje_booker_hub_protobufs_RequestType_GET_DELIVERY_TABLE = 10
} koje_booker_hub_protobufs_RequestType;

/* Struct definitions */
typedef struct _koje_booker_hub_protobufs_Request {
    uint64_t id;
    uint32_t version;
    koje_booker_hub_protobufs_RequestType type;
    bool has_params;
    pb_callback_t params;
} koje_booker_hub_protobufs_Request;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _koje_booker_hub_protobufs_RequestType_MIN koje_booker_hub_protobufs_RequestType_UNKNOWN_REQUEST_TYPE
#define _koje_booker_hub_protobufs_RequestType_MAX koje_booker_hub_protobufs_RequestType_GET_DELIVERY_TABLE
#define _koje_booker_hub_protobufs_RequestType_ARRAYSIZE ((koje_booker_hub_protobufs_RequestType)(koje_booker_hub_protobufs_RequestType_GET_DELIVERY_TABLE+1))

#define koje_booker_hub_protobufs_Request_type_ENUMTYPE koje_booker_hub_protobufs_RequestType


/* Initializer values for message structs */
#define koje_booker_hub_protobufs_Request_init_default {0, 0, _koje_booker_hub_protobufs_RequestType_MIN, 0, {{NULL}, NULL}}
#define koje_booker_hub_protobufs_Request_init_zero {0, 0, _koje_booker_hub_protobufs_RequestType_MIN, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define koje_booker_hub_protobufs_Request_id_tag 1
#define koje_booker_hub_protobufs_Request_version_tag 2
#define koje_booker_hub_protobufs_Request_type_tag 3
#define koje_booker_hub_protobufs_Request_has_params_tag 4
#define koje_booker_hub_protobufs_Request_params_tag 5

/* Struct field encoding specification for nanopb */
#define koje_booker_hub_protobufs_Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   version,           2) \
X(a, STATIC,   SINGULAR, UENUM,    type,              3) \
X(a, STATIC,   SINGULAR, BOOL,     has_params,        4) \
X(a, CALLBACK, SINGULAR, STRING,   params,            5)
#define koje_booker_hub_protobufs_Request_CALLBACK pb_default_field_callback
#define koje_booker_hub_protobufs_Request_DEFAULT NULL

extern const pb_msgdesc_t koje_booker_hub_protobufs_Request_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define koje_booker_hub_protobufs_Request_fields &koje_booker_hub_protobufs_Request_msg

/* Maximum encoded size of messages (where known) */
/* koje_booker_hub_protobufs_Request_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
