/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_KOJE_BOOKER_HUB_PROTOBUFS_RESERVATIONSTABLE_PB_H_INCLUDED
#define PB_KOJE_BOOKER_HUB_PROTOBUFS_RESERVATIONSTABLE_PB_H_INCLUDED
#include "nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _koje_booker_hub_protobufs_ReservationTableItem {
    char start_time[17];
    char end_time[17];
    char reserved_by[128];
} koje_booker_hub_protobufs_ReservationTableItem;

typedef struct _koje_booker_hub_protobufs_ReservationsTable {
    uint64_t id;
    uint32_t page;
    pb_size_t reservations_count;
    koje_booker_hub_protobufs_ReservationTableItem reservations[10];
} koje_booker_hub_protobufs_ReservationsTable;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define koje_booker_hub_protobufs_ReservationsTable_init_default {0, 0, 0, {koje_booker_hub_protobufs_ReservationTableItem_init_default, koje_booker_hub_protobufs_ReservationTableItem_init_default, koje_booker_hub_protobufs_ReservationTableItem_init_default, koje_booker_hub_protobufs_ReservationTableItem_init_default, koje_booker_hub_protobufs_ReservationTableItem_init_default, koje_booker_hub_protobufs_ReservationTableItem_init_default, koje_booker_hub_protobufs_ReservationTableItem_init_default, koje_booker_hub_protobufs_ReservationTableItem_init_default, koje_booker_hub_protobufs_ReservationTableItem_init_default, koje_booker_hub_protobufs_ReservationTableItem_init_default}}
#define koje_booker_hub_protobufs_ReservationTableItem_init_default {"", "", ""}
#define koje_booker_hub_protobufs_ReservationsTable_init_zero {0, 0, 0, {koje_booker_hub_protobufs_ReservationTableItem_init_zero, koje_booker_hub_protobufs_ReservationTableItem_init_zero, koje_booker_hub_protobufs_ReservationTableItem_init_zero, koje_booker_hub_protobufs_ReservationTableItem_init_zero, koje_booker_hub_protobufs_ReservationTableItem_init_zero, koje_booker_hub_protobufs_ReservationTableItem_init_zero, koje_booker_hub_protobufs_ReservationTableItem_init_zero, koje_booker_hub_protobufs_ReservationTableItem_init_zero, koje_booker_hub_protobufs_ReservationTableItem_init_zero, koje_booker_hub_protobufs_ReservationTableItem_init_zero}}
#define koje_booker_hub_protobufs_ReservationTableItem_init_zero {"", "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define koje_booker_hub_protobufs_ReservationTableItem_start_time_tag 1
#define koje_booker_hub_protobufs_ReservationTableItem_end_time_tag 2
#define koje_booker_hub_protobufs_ReservationTableItem_reserved_by_tag 3
#define koje_booker_hub_protobufs_ReservationsTable_id_tag 1
#define koje_booker_hub_protobufs_ReservationsTable_page_tag 2
#define koje_booker_hub_protobufs_ReservationsTable_reservations_tag 3

/* Struct field encoding specification for nanopb */
#define koje_booker_hub_protobufs_ReservationsTable_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   page,              2) \
X(a, STATIC,   REPEATED, MESSAGE,  reservations,      3)
#define koje_booker_hub_protobufs_ReservationsTable_CALLBACK NULL
#define koje_booker_hub_protobufs_ReservationsTable_DEFAULT NULL
#define koje_booker_hub_protobufs_ReservationsTable_reservations_MSGTYPE koje_booker_hub_protobufs_ReservationTableItem

#define koje_booker_hub_protobufs_ReservationTableItem_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   start_time,        1) \
X(a, STATIC,   SINGULAR, STRING,   end_time,          2) \
X(a, STATIC,   SINGULAR, STRING,   reserved_by,       3)
#define koje_booker_hub_protobufs_ReservationTableItem_CALLBACK NULL
#define koje_booker_hub_protobufs_ReservationTableItem_DEFAULT NULL

extern const pb_msgdesc_t koje_booker_hub_protobufs_ReservationsTable_msg;
extern const pb_msgdesc_t koje_booker_hub_protobufs_ReservationTableItem_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define koje_booker_hub_protobufs_ReservationsTable_fields &koje_booker_hub_protobufs_ReservationsTable_msg
#define koje_booker_hub_protobufs_ReservationTableItem_fields &koje_booker_hub_protobufs_ReservationTableItem_msg

/* Maximum encoded size of messages (where known) */
#define KOJE_BOOKER_HUB_PROTOBUFS_RESERVATIONSTABLE_PB_H_MAX_SIZE koje_booker_hub_protobufs_ReservationsTable_size
#define koje_booker_hub_protobufs_ReservationTableItem_size 166
#define koje_booker_hub_protobufs_ReservationsTable_size 1707

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
