/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_KOJE_BOOKER_HUB_PROTOBUFS_RESERVATIONSTATUS_PB_H_INCLUDED
#define PB_KOJE_BOOKER_HUB_PROTOBUFS_RESERVATIONSTATUS_PB_H_INCLUDED
#include "nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _koje_booker_hub_protobufs_ReservationStatus {
    koje_booker_hub_protobufs_ReservationStatus_UNKNOWN_RESERVATION_STATUS = 0,
    koje_booker_hub_protobufs_ReservationStatus_FREE = 1,
    koje_booker_hub_protobufs_ReservationStatus_RESERVED = 2,
    koje_booker_hub_protobufs_ReservationStatus_NEXT = 3
} koje_booker_hub_protobufs_ReservationStatus;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _koje_booker_hub_protobufs_ReservationStatus_MIN koje_booker_hub_protobufs_ReservationStatus_UNKNOWN_RESERVATION_STATUS
#define _koje_booker_hub_protobufs_ReservationStatus_MAX koje_booker_hub_protobufs_ReservationStatus_NEXT
#define _koje_booker_hub_protobufs_ReservationStatus_ARRAYSIZE ((koje_booker_hub_protobufs_ReservationStatus)(koje_booker_hub_protobufs_ReservationStatus_NEXT+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
