/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_KOJE_BOOKER_HUB_PROTOBUFS_RESERVATION_PB_H_INCLUDED
#define PB_KOJE_BOOKER_HUB_PROTOBUFS_RESERVATION_PB_H_INCLUDED
#include "nanopb/pb.h"
#include "ReservationStatus.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _koje_booker_hub_protobufs_Reservation {
    uint64_t id;
    koje_booker_hub_protobufs_ReservationStatus status;
    char reserved_by[128];
    char start_time[17];
    char end_time[17];
    char comment[128];
    char remark[128];
} koje_booker_hub_protobufs_Reservation;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define koje_booker_hub_protobufs_Reservation_init_default {0, _koje_booker_hub_protobufs_ReservationStatus_MIN, "", "", "", "", ""}
#define koje_booker_hub_protobufs_Reservation_init_zero {0, _koje_booker_hub_protobufs_ReservationStatus_MIN, "", "", "", "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define koje_booker_hub_protobufs_Reservation_id_tag 1
#define koje_booker_hub_protobufs_Reservation_status_tag 2
#define koje_booker_hub_protobufs_Reservation_reserved_by_tag 3
#define koje_booker_hub_protobufs_Reservation_start_time_tag 4
#define koje_booker_hub_protobufs_Reservation_end_time_tag 5
#define koje_booker_hub_protobufs_Reservation_comment_tag 6
#define koje_booker_hub_protobufs_Reservation_remark_tag 7

/* Struct field encoding specification for nanopb */
#define koje_booker_hub_protobufs_Reservation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2) \
X(a, STATIC,   SINGULAR, STRING,   reserved_by,       3) \
X(a, STATIC,   SINGULAR, STRING,   start_time,        4) \
X(a, STATIC,   SINGULAR, STRING,   end_time,          5) \
X(a, STATIC,   SINGULAR, STRING,   comment,           6) \
X(a, STATIC,   SINGULAR, STRING,   remark,            7)
#define koje_booker_hub_protobufs_Reservation_CALLBACK NULL
#define koje_booker_hub_protobufs_Reservation_DEFAULT NULL

extern const pb_msgdesc_t koje_booker_hub_protobufs_Reservation_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define koje_booker_hub_protobufs_Reservation_fields &koje_booker_hub_protobufs_Reservation_msg

/* Maximum encoded size of messages (where known) */
#define KOJE_BOOKER_HUB_PROTOBUFS_RESERVATION_PB_H_MAX_SIZE koje_booker_hub_protobufs_Reservation_size
#define koje_booker_hub_protobufs_Reservation_size 439

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
